UPDATE countries SET name_ta = 'கனடா' WHERE code = 'CA';
UPDATE countries SET name_ta = 'ஐக்கிய ராஜ்யம்' WHERE code = 'GB';
UPDATE countries SET name_ta = 'இலங்கை' WHERE code = 'LK';
UPDATE countries SET name_ta = 'இந்தியா' WHERE code = 'IN';
UPDATE countries SET name_ta = 'பிரான்ஸ்' WHERE code = 'FR';
UPDATE countries SET name_ta = 'ஜெர்மனி' WHERE code = 'DE';
UPDATE countries SET name_ta = 'ஸ்விட்சர்லாந்து' WHERE code = 'CH';
UPDATE countries SET name_ta = 'ஆஸ்திரேலியா' WHERE code = 'AU';
UPDATE countries SET name_ta = 'நார்வே' WHERE code = 'NO';
UPDATE countries SET name_ta = 'அமெரிக்கா' WHERE code = 'US';
UPDATE countries SET name_ta = 'ஆப்கானிஸ்தான்' WHERE code = 'AF';
UPDATE countries SET name_ta = 'அல்பேனியா' WHERE code = 'AL';
UPDATE countries SET name_ta = 'அல்ஜீரியா' WHERE code = 'DZ';
UPDATE countries SET name_ta = 'அந்தோரா' WHERE code = 'AD';
UPDATE countries SET name_ta = 'அங்கோலா' WHERE code = 'AO';
UPDATE countries SET name_ta = 'ஆன்டிகுவா மற்றும் பர்புடா' WHERE code = 'AG';
UPDATE countries SET name_ta = 'அர்ஜென்டினா' WHERE code = 'AR';
UPDATE countries SET name_ta = 'ஆர்மேனியா' WHERE code = 'AM';
UPDATE countries SET name_ta = 'ஆஸ்திரியா' WHERE code = 'AT';
UPDATE countries SET name_ta = 'அஜர்பைஜான்' WHERE code = 'AZ';
UPDATE countries SET name_ta = 'பஹாமாஸ்' WHERE code = 'BS';
UPDATE countries SET name_ta = 'பஹ்ரைன்' WHERE code = 'BH';
UPDATE countries SET name_ta = 'வங்காதேசம்' WHERE code = 'BD';
UPDATE countries SET name_ta = 'பர்படோஸ்' WHERE code = 'BB';
UPDATE countries SET name_ta = 'பெலாரஸ்' WHERE code = 'BY';
UPDATE countries SET name_ta = 'பெல்ஜியம்' WHERE code = 'BE';
UPDATE countries SET name_ta = 'பெலிச்' WHERE code = 'BZ';
UPDATE countries SET name_ta = 'பெனின்' WHERE code = 'BJ';
UPDATE countries SET name_ta = 'பூடான்' WHERE code = 'BT';
UPDATE countries SET name_ta = 'பொலிவியா' WHERE code = 'BO';
UPDATE countries SET name_ta = 'போஸ்னியா மற்றும் ஹெர்சகோவினா' WHERE code = 'BA';
UPDATE countries SET name_ta = 'போட்ஸ்வானா' WHERE code = 'BW';
UPDATE countries SET name_ta = 'பிரேசில்' WHERE code = 'BR';
UPDATE countries SET name_ta = 'புரூணை' WHERE code = 'BN';
UPDATE countries SET name_ta = 'பல்கேரியா' WHERE code = 'BG';
UPDATE countries SET name_ta = 'புர்கினா ஃபாசோ' WHERE code = 'BF';
UPDATE countries SET name_ta = 'புருண்டி' WHERE code = 'BI';
UPDATE countries SET name_ta = 'கேப் வர்தே' WHERE code = 'CV';
UPDATE countries SET name_ta = 'கம்போடியா' WHERE code = 'KH';
UPDATE countries SET name_ta = 'கேமரூன்' WHERE code = 'CM';
UPDATE countries SET name_ta = 'மத்திய ஆப்பிரிக்க குடியரசு' WHERE code = 'CF';
UPDATE countries SET name_ta = 'சாட்' WHERE code = 'TD';
UPDATE countries SET name_ta = 'சிலி' WHERE code = 'CL';
UPDATE countries SET name_ta = 'சீனா' WHERE code = 'CN';
UPDATE countries SET name_ta = 'கொலம்பியா' WHERE code = 'CO';
UPDATE countries SET name_ta = 'கொமோரோஸ்' WHERE code = 'KM';
UPDATE countries SET name_ta = 'காங்கோ' WHERE code = 'CG';
UPDATE countries SET name_ta = 'கோஸ்டாரிகா' WHERE code = 'CR';
UPDATE countries SET name_ta = 'குரோஷியா' WHERE code = 'HR';
UPDATE countries SET name_ta = 'கியூபா' WHERE code = 'CU';
UPDATE countries SET name_ta = 'சைப்ரஸ்' WHERE code = 'CY';
UPDATE countries SET name_ta = 'செக் குடியரசு' WHERE code = 'CZ';
UPDATE countries SET name_ta = 'டென்மார்க்' WHERE code = 'DK';
UPDATE countries SET name_ta = 'ஜிபூட்டி' WHERE code = 'DJ';
UPDATE countries SET name_ta = 'டொமினிகா' WHERE code = 'DM';
UPDATE countries SET name_ta = 'டொமினிகன் குடியரசு' WHERE code = 'DO';
UPDATE countries SET name_ta = 'எக்வடோர்' WHERE code = 'EC';
UPDATE countries SET name_ta = 'எகிப்து' WHERE code = 'EG';
UPDATE countries SET name_ta = 'எல் சல்வடோர்' WHERE code = 'SV';
UPDATE countries SET name_ta = 'கினியா' WHERE code = 'GQ';
UPDATE countries SET name_ta = 'எரித்திரியா' WHERE code = 'ER';
UPDATE countries SET name_ta = 'எஸ்டோனியா' WHERE code = 'EE';
UPDATE countries SET name_ta = 'எஸ்வாட்டினி' WHERE code = 'SZ';
UPDATE countries SET name_ta = 'எத்தியோப்பியா' WHERE code = 'ET';
UPDATE countries SET name_ta = 'ஃபிஜி' WHERE code = 'FJ';
UPDATE countries SET name_ta = 'ஃபின்லாந்து' WHERE code = 'FI';
UPDATE countries SET name_ta = 'கேபான்' WHERE code = 'GA';
UPDATE countries SET name_ta = 'கேம்பியா' WHERE code = 'GM';
UPDATE countries SET name_ta = 'ஜார்ஜியா' WHERE code = 'GE';
UPDATE countries SET name_ta = 'கானா' WHERE code = 'GH';
UPDATE countries SET name_ta = 'கிரீஸ்' WHERE code = 'GR';
UPDATE countries SET name_ta = 'கிரெனடா' WHERE code = 'GD';
UPDATE countries SET name_ta = 'குவாத்தமாலா' WHERE code = 'GT';
UPDATE countries SET name_ta = 'கினியா' WHERE code = 'GN';
UPDATE countries SET name_ta = 'கினியா-பிசாவ்' WHERE code = 'GW';
UPDATE countries SET name_ta = 'கயானா' WHERE code = 'GY';
UPDATE countries SET name_ta = 'ஹெய்டி' WHERE code = 'HT';
UPDATE countries SET name_ta = 'திரு ஆசனம்' WHERE code = 'VA';
UPDATE countries SET name_ta = 'ஹொண்டுராஸ்' WHERE code = 'HN';
UPDATE countries SET name_ta = 'ஹங்கேரி' WHERE code = 'HU';
UPDATE countries SET name_ta = 'ஐஸ்லாந்து' WHERE code = 'IS';
UPDATE countries SET name_ta = 'இந்தோனேசியா' WHERE code = 'ID';
UPDATE countries SET name_ta = 'ஈரான்' WHERE code = 'IR';
UPDATE countries SET name_ta = 'ஈராக்' WHERE code = 'IQ';
UPDATE countries SET name_ta = 'அயர்லாந்து' WHERE code = 'IE';
UPDATE countries SET name_ta = 'இஸ்ரேல்' WHERE code = 'IL';
UPDATE countries SET name_ta = 'இத்தாலி' WHERE code = 'IT';
UPDATE countries SET name_ta = 'ஜமேக்கா' WHERE code = 'JM';
UPDATE countries SET name_ta = 'ஜப்பான்' WHERE code = 'JP';
UPDATE countries SET name_ta = 'ஜோர்தான்' WHERE code = 'JO';
UPDATE countries SET name_ta = 'கஜகஸ்தான்' WHERE code = 'KZ';
UPDATE countries SET name_ta = 'கென்யா' WHERE code = 'KE';
UPDATE countries SET name_ta = 'கிரிபடி' WHERE code = 'KI';
UPDATE countries SET name_ta = 'குவைத்' WHERE code = 'KW';
UPDATE countries SET name_ta = 'கிர்கிஸ்தான்' WHERE code = 'KG';
UPDATE countries SET name_ta = 'லாவோஸ்' WHERE code = 'LA';
UPDATE countries SET name_ta = 'லாட்வியா' WHERE code = 'LV';
UPDATE countries SET name_ta = 'லெபனான்' WHERE code = 'LB';
UPDATE countries SET name_ta = 'லெசோதோ' WHERE code = 'LS';
UPDATE countries SET name_ta = 'லைபீரியா' WHERE code = 'LR';
UPDATE countries SET name_ta = 'லிபியா' WHERE code = 'LY';
UPDATE countries SET name_ta = 'லிக்டன்ஸ்டைன்' WHERE code = 'LI';
UPDATE countries SET name_ta = 'லித்துவேனியா' WHERE code = 'LT';
UPDATE countries SET name_ta = 'லக்ஸம்பர்க்' WHERE code = 'LU';
UPDATE countries SET name_ta = 'மடகாஸ்கர்' WHERE code = 'MG';
UPDATE countries SET name_ta = 'மலாவி' WHERE code = 'MW';
UPDATE countries SET name_ta = 'மலேசியா' WHERE code = 'MY';
UPDATE countries SET name_ta = 'மால்தீவு' WHERE code = 'MV';
UPDATE countries SET name_ta = 'மாலி' WHERE code = 'ML';
UPDATE countries SET name_ta = 'மால்டா' WHERE code = 'MT';
UPDATE countries SET name_ta = 'மார்ஷல் தீவுகள்' WHERE code = 'MH';
UPDATE countries SET name_ta = 'மொரிசியானா' WHERE code = 'MR';
UPDATE countries SET name_ta = 'மொரிஷியஸ்' WHERE code = 'MU';
UPDATE countries SET name_ta = 'மெக்ஸிகோ' WHERE code = 'MX';
UPDATE countries SET name_ta = 'மைக்ரோனேஷியா' WHERE code = 'FM';
UPDATE countries SET name_ta = 'மல்தோவா' WHERE code = 'MD';
UPDATE countries SET name_ta = 'மொனாகோ' WHERE code = 'MC';
UPDATE countries SET name_ta = 'மங்கோலியா' WHERE code = 'MN';
UPDATE countries SET name_ta = 'மான்டெனிக்ரோ' WHERE code = 'ME';
UPDATE countries SET name_ta = 'மொரோக்கோ' WHERE code = 'MA';
UPDATE countries SET name_ta = 'மொசாம்பிக்' WHERE code = 'MZ';
UPDATE countries SET name_ta = 'மியான்மர்' WHERE code = 'MM';
UPDATE countries SET name_ta = 'நமீபியா' WHERE code = 'NA';
UPDATE countries SET name_ta = 'நவ்வு' WHERE code = 'NR';
UPDATE countries SET name_ta = 'நேபாளம்' WHERE code = 'NP';
UPDATE countries SET name_ta = 'நெதர்லாந்து' WHERE code = 'NL';
UPDATE countries SET name_ta = 'நியூசிலாந்து' WHERE code = 'NZ';
UPDATE countries SET name_ta = 'நிகரகுவா' WHERE code = 'NI';
UPDATE countries SET name_ta = 'நைஜர்' WHERE code = 'NE';
UPDATE countries SET name_ta = 'நைஜீரியா' WHERE code = 'NG';
UPDATE countries SET name_ta = 'வட கொரியா' WHERE code = 'KP';
UPDATE countries SET name_ta = 'வட மக்கேடோனியா' WHERE code = 'MK';
UPDATE countries SET name_ta = 'ஒமன்' WHERE code = 'OM';
UPDATE countries SET name_ta = 'பாகிஸ்தான்' WHERE code = 'PK';
UPDATE countries SET name_ta = 'பலாவு' WHERE code = 'PW';
UPDATE countries SET name_ta = 'பாலஸ்தீனம்' WHERE code = 'PS';
UPDATE countries SET name_ta = 'பனாமா' WHERE code = 'PA';
UPDATE countries SET name_ta = 'பப்புவா நியூ கினியா' WHERE code = 'PG';
UPDATE countries SET name_ta = 'பராகுவே' WHERE code = 'PY';
UPDATE countries SET name_ta = 'பெரு' WHERE code = 'PE';
UPDATE countries SET name_ta = 'பிலிப்பைன்ஸ்' WHERE code = 'PH';
UPDATE countries SET name_ta = 'போலந்து' WHERE code = 'PL';
UPDATE countries SET name_ta = 'போர்த்துகல்' WHERE code = 'PT';
UPDATE countries SET name_ta = 'கத்தார்' WHERE code = 'QA';
UPDATE countries SET name_ta = 'ருமேனியா' WHERE code = 'RO';
UPDATE countries SET name_ta = 'ரஷ்யா' WHERE code = 'RU';
UPDATE countries SET name_ta = 'ருவாண்டா' WHERE code = 'RW';
UPDATE countries SET name_ta = 'செயின்ட் கிட்ஸ் மற்றும் நெவிஸ்' WHERE code = 'KN';
UPDATE countries SET name_ta = 'செயின்ட் லூசியா' WHERE code = 'LC';
UPDATE countries SET name_ta = 'செயின்ட் வின்சென்ட் மற்றும் கிரெனடீன்ஸ்' WHERE code = 'VC';
UPDATE countries SET name_ta = 'சமோவா' WHERE code = 'WS';
UPDATE countries SET name_ta = 'சான் மரீனோ' WHERE code = 'SM';
UPDATE countries SET name_ta = 'சாவ் டோமே மற்றும் பிரின்சிப்பி' WHERE code = 'ST';
UPDATE countries SET name_ta = 'சவுதி அரேபியா' WHERE code = 'SA';
UPDATE countries SET name_ta = 'செனகல்' WHERE code = 'SN';
UPDATE countries SET name_ta = 'செர்பியா' WHERE code = 'RS';
UPDATE countries SET name_ta = 'சீஷெல்ஸ்' WHERE code = 'SC';
UPDATE countries SET name_ta = 'சியேரா லியோன்' WHERE code = 'SL';
UPDATE countries SET name_ta = 'சிங்கப்பூர்' WHERE code = 'SG';
UPDATE countries SET name_ta = 'ஸ்லோவாகியா' WHERE code = 'SK';
UPDATE countries SET name_ta = 'ஸ்லோவேனியா' WHERE code = 'SI';
UPDATE countries SET name_ta = 'சாலமன் தீவுகள்' WHERE code = 'SB';
UPDATE countries SET name_ta = 'சோமாலியா' WHERE code = 'SO';
UPDATE countries SET name_ta = 'தென் ஆப்பிரிக்கா' WHERE code = 'ZA';
UPDATE countries SET name_ta = 'தென் கொரியா' WHERE code = 'KR';
UPDATE countries SET name_ta = 'தென் சூடான்' WHERE code = 'SS';
UPDATE countries SET name_ta = 'ஸ்பெயின்' WHERE code = 'ES';
UPDATE countries SET name_ta = 'சூடான்' WHERE code = 'SD';
UPDATE countries SET name_ta = 'சுரினாம்' WHERE code = 'SR';
UPDATE countries SET name_ta = 'ஸ்வீடன்' WHERE code = 'SE';
UPDATE countries SET name_ta = 'சிரியா' WHERE code = 'SY';
UPDATE countries SET name_ta = 'தஜிகிஸ்தான்' WHERE code = 'TJ';
UPDATE countries SET name_ta = 'தான்சானியா' WHERE code = 'TZ';
UPDATE countries SET name_ta = 'தாய்லாந்து' WHERE code = 'TH';
UPDATE countries SET name_ta = 'கிழக்கு திமோர்' WHERE code = 'TL';
UPDATE countries SET name_ta = 'டோகோ' WHERE code = 'TG';
UPDATE countries SET name_ta = 'டோங்கா' WHERE code = 'TO';
UPDATE countries SET name_ta = 'டிரினிடாட் மற்றும் டோபாகோ' WHERE code = 'TT';
UPDATE countries SET name_ta = 'துனிசியா' WHERE code = 'TN';
UPDATE countries SET name_ta = 'துருக்கி' WHERE code = 'TR';
UPDATE countries SET name_ta = 'துர்க்மெனிஸ்தான்' WHERE code = 'TM';
UPDATE countries SET name_ta = 'துவாலு' WHERE code = 'TV';
UPDATE countries SET name_ta = 'உகாண்டா' WHERE code = 'UG';
UPDATE countries SET name_ta = 'உக்ரைன்' WHERE code = 'UA';
UPDATE countries SET name_ta = 'நாடுகள் அரபு கூட்டமைப்பு' WHERE code = 'AE';
UPDATE countries SET name_ta = 'உருகுவே' WHERE code = 'UY';
UPDATE countries SET name_ta = 'உஸ்பெகிஸ்தான்' WHERE code = 'UZ';
UPDATE countries SET name_ta = 'வனுவாட்டு' WHERE code = 'VU';
UPDATE countries SET name_ta = 'வெனிசுவேலா' WHERE code = 'VE';
UPDATE countries SET name_ta = 'வியட்நாம்' WHERE code = 'VN';
UPDATE countries SET name_ta = 'யேமன்' WHERE code = 'YE';
UPDATE countries SET name_ta = 'சாம்பியா' WHERE code = 'ZM';
UPDATE countries SET name_ta = 'ஜிம்பாப்வே' WHERE code = 'ZW';
